theme = 'hugo-theme-stack'
enableGitInfo = true
title = "Blog de Vida"
languageCode = "es"
defaultContentLanguage = "es"

[author]
 name = "Andrés Hurtado A

[params]
 mainSections = ["post"]
 description = "Lo que rescato de mi diario. Apuntes de memoria"

[params.sidebar]
 emoji = "✍️"
 subtitle = "Lo que rescato de mi diario. Apuntes de memoria

[params.avatar]
 enabled = true
 local = true
 src = "img/avatar.jpg"
